// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2632.MyRobot.subsystems;


//import org.usfirst.frc2632.MyRobot.OI;
import org.usfirst.frc2632.MyRobot.RobotMap;
import org.usfirst.frc2632.MyRobot.commands.*;
//import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.SpeedControllerGroup;
import edu.wpi.first.wpilibj.GenericHID.Hand;
import edu.wpi.first.wpilibj.XboxController;


import com.ctre.phoenix.motorcontrol.can.*;


import edu.wpi.first.wpilibj.drive.DifferentialDrive;



/**
 *
 */
public class DriveTrainSubsystem extends Subsystem {

    
    private WPI_TalonSRX LRSpeedController;
    private WPI_TalonSRX LFSpeedController;
    private WPI_TalonSRX RRSpeedController;
    private WPI_TalonSRX RFSpeedController;
    private DifferentialDrive driveTrain;

    public DriveTrainSubsystem() {

        //The two letters in front of speed controller stand for its location 
        //ie. LF=Left Front, RR= Right Rear.
        LFSpeedController = new WPI_TalonSRX(RobotMap.LFMOTORCONTROLLER);
        LRSpeedController = new WPI_TalonSRX(RobotMap.LRMOTORCONTROLLER);
        LRSpeedController.setInverted(false);
        LFSpeedController.setInverted(false);
        
        RFSpeedController = new WPI_TalonSRX(RobotMap.RFMOTORCONTROLLER);
        RRSpeedController = new WPI_TalonSRX(RobotMap.RRMOTORCONTROLLER);
        RRSpeedController.setInverted(false);
        RFSpeedController.setInverted(false);
        
        //This combines the speed controllers into groups so they can be controlled with a differential drive object.
        SpeedControllerGroup LeftSpeedControllers = new SpeedControllerGroup(LFSpeedController, LRSpeedController);
        SpeedControllerGroup RightSpeedControllers = new SpeedControllerGroup(RFSpeedController, RRSpeedController);

        driveTrain = new DifferentialDrive(LeftSpeedControllers, RightSpeedControllers);
        driveTrain.setRightSideInverted(false);

    }

    @Override
    public void initDefaultCommand() {
        
        // Sets the default command to drive so the robot is always running the drive command with input from the joysticks
        //If the robot is not moving then it is just getting the values 0,0, but still running the command.
         setDefaultCommand(new Drive());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop
        
    }

    //4 drive methods, 2 tank and 2 arcade
    //Each type of driving has two options, take an Xbox Controller object and get the values 
    //Or justs take in two numbers.
    public void tank(double leftSpeed, double rightSpeed){
        driveTrain.tankDrive(leftSpeed, rightSpeed);

    }
    public void tank(XboxController controller){
        tank(-(controller.getY(Hand.kLeft)*.75), (controller.getY(Hand.kRight)*.75));

    }
    public void arcade(XboxController controller){
        driveTrain.arcadeDrive((controller.getX(Hand.kLeft)*.75), (controller.getY(Hand.kLeft)*.75));
    }
    public void arcade(double rotation, double throttle){
        driveTrain.arcadeDrive(rotation, throttle);
    }

}

